version: '3'
services:
  battle:
    build:
      context: ./
      dockerfile: dockerfile.battle
    volumes: 
      - .:/app  # mount local dir as volume
      - ./battle/:/app/main
    depends_on:
      - kafka

  hero:
    build: 
      context: ./
      dockerfile: dockerfile.character
    volumes: 
      - .:/app
      - ./character/:/app/character
    depends_on:
      - battle

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # For single replica kafka cluster
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CREATE_TOPICS: "battle:1:1,hero:1:1"  # doesn't work?
    depends_on:
      - zookeeper


  