version: '3'
services:
  battle_main:
    build: .
    volumes: 
      - .:/app
  # hero:
  #   build: .
  #   volumes:
  #     - ./hero:/app
  # enemy:
  #   build: .
  #   volumes:
  #     - ./enemy:/app

  